[package]
name = "sqd-assignments"
license = "AGPL-3.0-or-later"
version = "0.0.1"
edition = "2021"

[features]
reader = []
builder = []

[dependencies]
anyhow = { version = "1.0" }
crypto_box = { version = "0.9.1", optional = true }
curve25519-dalek = { version = "4.1.3", optional = true }
flatbuffers = "25.2.10"
hmac = { version = "0.12.1", optional = true }
libp2p-identity = { workspace = true, features = ["rand"] }
