[package]
name = "sqd-keygen"
license = "AGPL-3.0-or-later"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
libp2p = { workspace = true, features = [] }

[lints]
workspace = true
