[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
libp2p = { version = "0.56.0" }
libp2p-core = { version = "0.43.1" }
libp2p-identity = { version = "0.2.12", features = ["peerid"] }
libp2p-connection-limits = { version = "0.6.0" }
libp2p-swarm = { version = "0.47.0" }
libp2p-swarm-derive = { version = "0.35.1" }
libp2p-swarm-test = { version = "0.6.0" }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
cast_possible_truncation = "warn"
dbg_macro = "warn"
explicit_iter_loop = "warn"
inefficient_to_string = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
needless_pass_by_value = "warn"
redundant_closure_for_method_calls = "warn"
type_repetition_in_bounds = "warn"
use_self = "warn"
used_underscore_binding = "warn"
