@startuml pallet-whead

collections Runtime

frame PalletNNBReq

frame PalletWorker {
  interface WorkerInterface
}

frame PalletWhead {

  component Storage {
    card Status {
      card WorkerWaiting
      card InProgress as "InProgress(Vec<WorkerId>)"
    }
    storage RequestsProgress as "HashMap<Request, Status>" << RequestsProgress >>
  }

  interface WheadInterface
}

PalletNNBReq -right- WheadInterface

WheadInterface -- WorkerInterface

WheadInterface -left- Storage

Runtime -up- WheadInterface

@enduml
