@startuml pallet-worker

collections Runtime

cloud WorkerCandidate
cloud Worker

frame PalletWorker {
  component Calls {
    card register
    card update_da
  }

  component Storage {
    storage VecWorkersId as "Vec<WorkerId>" << Workers >>
    storage MapWorkersDA as "HashMap<WorkerId, Data>" << Data availability >>
  }

  interface WorkerInterface
}

WorkerInterface -left- Storage

register -- VecWorkersId
update_da -- MapWorkersDA

WorkerCandidate -- register
Worker -- update_da

Runtime -up- WorkerInterface

@enduml
