@startuml pallet-nnbreq

collections Runtime

cloud Client

frame PalletWhead {
  interface WheadInterface
}


frame PalletNNBReq {

  component Calls {
    card get_data
  }

  component Storage {
    storage Requests as "HashMap<RequestId, Status>" << Requests >>
  }

  interface NNBReqInterface
}

Client -- get_data

get_data -- Requests

NNBReqInterface -left- Storage

Runtime -up- NNBReqInterface

NNBReqInterface -- WheadInterface

@enduml
