@startuml become_archive

participant ArchiveCandidate as "ArchiveCandidate Alice"

box "Subsquid Network (Validators)"
  participant Node
  participant Validators
end box

box "Subsquid Network (Storage)"
  participant PalletStaking
  participant PalletArchive
end box

ArchiveCandidate -> ArchiveCandidate: Prepare transaction\nto become an archive\nthat proves a required\ndocker image is run.

ArchiveCandidate -> Node: Trx BeA: [be_archive(Alice, Signature)]
Node -> Validators: Propagate Trx BeA

Validators -> Validators: Verify Trx BeA
Validators -> PalletArchive: Try to apply BeA

PalletArchive -> PalletArchive: Verify if already is archive
PalletArchive -> PalletStaking: Verify that staked balance is enough
PalletStaking -> PalletArchive: Ok

PalletArchive -> Validators: Ok
Validators -> Validators: Apply valid Trx BeA

Validators -> Node: Trx BeA is in block
Node -> ArchiveCandidate: Success



@enduml
